# Generated by Django 3.2.2 on 2021-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='../media/james.jpg', upload_to=''),
        ),
    ]
