# Generated by Django 3.2.2 on 2021-05-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getImage', '0003_auto_20210516_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
